#!/bin/bash
export PATH="/bin:/sbin:/usr/sbin:/usr/bin"
BLACKLIST="/etc/ppp/vpn_blacklist"
if [ "$1" = "update" ]; then
	SUFFIX=`cat /tmp/vpn_route_suffix`
else
	SUFFIX=`ip route | sed -n 's/^default via \([0-9\.]*\) dev \([^ ]*\).*/via \1 dev \2/p'`
fi
if [ ! -e "/tmp/vpn_route_suffix" ]; then
	echo ${SUFFIX} > /tmp/vpn_route_suffix
fi
if [ ! -e ${BLACKLIST} ]; then
	exit 0
fi
for ip in `python /etc/ppp/read_vpn_blacklist.py < ${BLACKLIST}`; do
	ip route replace ${ip} ${SUFFIX}
done
